# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcsg324-3

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/lalala/ElectricPasswordLock/ElectricPasswordLock.cache/wt [current_project]
set_property parent.project_path D:/lalala/ElectricPasswordLock/ElectricPasswordLock.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/lalala/ElectricPasswordLock/ElectricPasswordLock.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib D:/lalala/ElectricPasswordLock/ElectricPasswordLock.srcs/sources_1/new/qwer.v
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top qwer -part xc7a35tcsg324-3


write_checkpoint -force -noxdef qwer.dcp

catch { report_utilization -file qwer_utilization_synth.rpt -pb qwer_utilization_synth.pb }
